---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-uat
  labels:
    app: myapp-uat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-uat
  template:
    metadata:
      labels:
        app: myapp-uat
    spec:
      containers:
        - name: myapp-uat
          image: nginx
          ports:
            - containerPort: 8080