kind: Service
apiVersion: v1
metadata:
  name: myapp-uat-service
  labels:
    app: myapp-uat
spec:
  selector:
    app: myapp-uat
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080